#!/bin/bash
#
#  generate a splunk query to view all logs from all nodes participating in a 
#  given job over the time the job was active
#
earliest=$(awk 'BEGIN {n=0} /Job Run/ {if ( n==0 ) { printf("%s:%s", $1, $2); n++}}' $1)
latest=$(tail -n1 $1 | awk '{printf("%s:%s", $1, $2)}')
pcregrep -o 'exec_host=[^\s]+' $1 | \
    sed -e 's/+/\n/g' | \
    sed -e 's#/[0-9]*$##' | \
    sed -e 's/exec_host=//' | \
    sort -u | \
    awk '
BEGIN { n=0 } 
{
  if ( n == 0 ) { printf( "(" ) }
  if ( n > 0 ) { printf( " OR " ) }
  printf("host=%s.sdsc.edu", $1);
  n++;
}
END { printf(") AND NOT sshd AND NOT crond AND NOT audit AND NOT 411-alert-handler AND NOT suppressed") }'
echo "earliest=$earliest latest=$latest"
